### ISSUE TITLE
需求描述

### ISSUE THREAD

**Issue by wxgg** [iuap-design/ucf-web-migrate#1]
## ucf-web-migrate 

一个 CLI 工具，旨在帮助uba开发者用户快速将其工程迁移升级为 ucf-web 微前端框架。

## 使用方式

```
# 全局安装
$ npm i ucf-web-migrate  -g

# 进入到原基于uba的工程跟目录下执行 migrate 
$ cd xx && migrate init
```

### 一、修改原工程的目录结构和文件，替换为遵循ucf-web框架规范的目录名称和文件名称；
1、删除`mock`目录、`.babelrc`文件、`postcss.config.js`文件、`uba.mock.js`文件、`node_modules`目录。
2、新增目录 `ucf-common`，并执行 `mv src ucf-common`
3、新增`ucf-apps`目录，执行 `mv ucf-common/src/pages/* ucf-apps`
4、读取uba.config.js文件内容并将其删除，同时新增默认的ucf.config.js文件

### 二、修改配置文件
1、读取并修改 `package.json`
1.1 读取`dependencies`配置
1.2 修改`scripts`字段，新增`ucf-scripts`的依赖。

2、读取`uba.config.js`中的配置，替换修改为ucf.config.js的配置，主要修改点：
2.1 context 读取和修改
2.2 proxy 读取和修改
2.3 global 环境变量读取和修改
2.4 alias 别名读取和修改（**这个影响点较大，修改后需要去自动化替换业务文件中的代码**）

### 三、修改业务代码原文件（公共资源的依赖路径）

```
# 如原配置的别名为：
utils: path.resolve(__dirname, 'src/utils/'),

....

# 对应的代码
import { Generate } from 'utils';
```

>参考：https://github.com/iuap-design/ucf-web/issues/2#issue-412721157

**Comment by kvkens** [comment]
几点建议： @wxgg @GuoYongfeng 

1. 文件操作使用：https://www.npmjs.com/package/fs-extra
2. 读取用户`uba.config.js`配置文件，按照对象操作节点，读取后，转回`ucf.config.js`保存，操作都可以用fs-extra
3. 同步、异步使用async/await
4. 任何操作用户的数据，一定要备份，增加备份目录`原始名称_bak_日期`类似
5. 不要对原始文件进行任何操作，只有read权限，生成额外给用户
6. 要明确目前项目依赖uba有多页、单页两种

**Comment by wxgg** [comment]
> 几点建议：@wxgg @GuoYongfeng
> 
> 1. 文件操作使用：[https](https://www.npmjs.com/package/fs-extra)：[//www.npmjs.com/package/fs-extra](https://www.npmjs.com/package/fs-extra)
> 2. 用户读取`uba.config.js`配置文件，按照对象操作节点，读取后，转回`ucf.config.js`保存，操作都可以用FS-EXTRA
> 3. 同步，异步使用异步/ AWAIT
> 4. 任何操作用户的数据，一定要备份，备份增加目录`原始名称_bak_日期`类似
> 5. 不要对原始文件进行任何操作，只有读权限，生成额外给用户
> 6. 要明确目前项目依赖UBA有多页，单页两种

疑问：
- 第三条是对cli工具内部的要求还是待转换项目的要求。
- 第四条是指用户的mock数据，还是备份转换之前的所有内容。
- 第六条是指现在UBA的项目会存在多页和单页两种情况，要同时兼容对吗？

**Comment by wxgg** [comment]
最新正式版已经发布，请版本参说明文档。
